### ISSUE TITLE
https://erfur.github.io/2019/03/28/down_the_rabbit_hole_pt3.html is not accessible anymore 

### ISSUE THREAD

**Issue by coaxial** [erfur/obsidian-ssl-unpin#35]
Hey, this is not really an issue but I don't know how else to get in touch :)

You had a guide about modifying Lenovo ThinkPad BIOSes at https://erfur.github.io/2019/03/28/down_the_rabbit_hole_pt3.html but the page is gone... Any way to get the contents still? The archive.org website doesn't have a copy.

Thanks!

**Comment by erfur** [comment]
Hi, thanks for getting in touch! I recently changed the repository to private, thinking that it was still possible to host github pages from a private repository. Thanks to you I just realized that's not the case. I made it public again, the link should be up now :)
